services:
  mysql-db:
    image: mysql:8.0
    container_name: lineup-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lineup
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: lineup-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  mysql_data:
